### ISSUE TITLE
Call to a smart-contract method fails with error code 12 EVMC_PRECOMPILE_FAILURE

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#1]
I'm trying to deploy following smart-contract and the deployment worked after a small workaround, but calling the method fails.

Smart-contract code: https://gist.github.com/Kuzirashi/4ecc4f9f7b6fbdc60d3ba9384ca226a8
Compiled smart-contract artifacts including bytecode and abi: https://gist.github.com/Kuzirashi/282610d5d34aca64d7d991a68805ca6a

![image](https://user-images.githubusercontent.com/4950658/114585503-03e6b700-9c84-11eb-8ce8-42a3373c17f1.png)

```
const contract = new web3.eth.Contract( HeadTail.abi, HeadTail.address );

function get() {
    contract.methods.userOneAddress().call();
}

function set() {
    contract.methods.depositUserOne().send({
      from: ethereum.selectedAddress,
      gas: 5000000,
      value: '0x01'
    });
}
```

```
godwoken_1   | [contract debug]: BEGIN set_storage
godwoken_1   | [contract debug]: END set_storage
godwoken_1   | [contract debug]: BEGIN get_storage
godwoken_1   | [contract debug]: END get_storage
godwoken_1   | [contract debug]: BEGIN set_storage
godwoken_1   | [contract debug]: END set_storage
godwoken_1   | [contract debug]: from_id => 5
godwoken_1   | [contract debug]: to_id => 7
godwoken_1   | [contract debug]: transfer value => 777
godwoken_1   | [contract debug]: transfer failed
godwoken_1   | [2021-04-13T16:13:06.133Z] [error] JSONRPC Server Error: Error: Chain submit L2Transaction failed: invalid exit code 12 Error: Chain submit L2Transaction failed: invalid exit code 12
godwoken_1   |     at ChainService.submitL2Transaction (/code/godwoken/packages/godwoken/lib/index.js:36:40)
godwoken_1   |     at JsonrpcServer.submitL2Transaction (/code/godwoken/packages/runner/src/jsonrpc_server.ts:75:36)
godwoken_1   |     at PromiseServer.<anonymous> (/code/godwoken/packages/runner/src/jsonrpc_server.ts:59:34)
godwoken_1   |     at module.exports.Method.execute (/code/godwoken/packages/runner/node_modules/jayson/lib/method.js:127:18)
godwoken_1   |     at module.exports.PromiseMethod.execute (/code/godwoken/packages/runner/node_modules/jayson/promise/lib/method.js:39:51)
godwoken_1   |     at /code/godwoken/packages/runner/node_modules/jayson/lib/server/index.js:315:12
godwoken_1   |     at maybeParse (/code/godwoken/packages/runner/node_modules/jayson/lib/server/index.js:440:5)
godwoken_1   |     at PromiseServer.Server.call (/code/godwoken/packages/runner/node_modules/jayson/lib/server/index.js:243:3)
godwoken_1   |     at /code/godwoken/packages/runner/node_modules/jayson/lib/server/middleware.js:36:12
godwoken_1   |     at call (/code/godwoken/node_modules/connect/index.js:239:7)
```

I see the error code meaning can be found here: https://github.com/ethereum/evmc/blob/5915690317989b02fd73d5aa338e4edfa120a452/include/evmc/evmc.h#L211 and is:
```
EVMC_PRECOMPILE_FAILURE = 12,
```

**Comment by RetricSu** [comment]
0.0.6 polyjuice is too old and buggy. later when we upgrade kicker to targeting the latest master branch of godwoken, this should get fixed.

**Comment by RetricSu** [comment]
I have reproduce this problem, it turns out it is not triggering polyjuice bug but a createCreator wrong param problem in godwoken-kicker. I will pull a quick fix for this  soon.

**Comment by RetricSu** [comment]
@Kuzirashi update to latest godwoken-kicker should fix.

**Comment by Kuzirashi** [comment]
Solved.
