### ISSUE TITLE
Can't deploy contracts using Brownie (estimate gas/call revert 12 status code)

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#23]
Repository with instructions: https://github.com/Kuzirashi/brownie-contract-deploy-godwoken

When trying to deploy Solidity smart-contracts using Brownie there's an error when trying to estimate gas for the deployment:
```
brownie run scripts/deploy --network godwokendev
Brownie v1.14.6 - Python development framework for Ethereum

ContractProject is the active project.
Enter the password to unlock this account: 

Running 'scripts/deploy.py::main'...
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 57, in main
    [coin_a, coin_b, coin_c, x_token] = deploy_tokens(_tx_params())
  File "./scripts/deploy.py", line 30, in deploy_tokens
    coin_a = ERC20.deploy("XYZ", "XYZ", 18, tx_params)
  File "brownie/network/contract.py", line 593, in __call__
    return tx["from"].deploy(
  File "brownie/network/account.py", line 465, in deploy
    exc = VirtualMachineError(e)
  File "brownie/exceptions.py", line 118, in __init__
    raise ValueError(str(exc)) from None
ValueError: Gas estimation failed: 'Internal error'. This transaction will likely revert. If you wish to broadcast, you must set the gas limit manually.
```

web3 docker service log:
```
web3_1                 | [1] POST / 200 0.294 ms - 36
web3_1                 | [1] fromId: 0x5
web3_1                 | [1] rawL2Transaction: {
web3_1                 | [1]   "from_id": "0x5",
web3_1                 | [1]   "to_id": "0x3",
web3_1                 | [1]   "nonce": "0x0",
web3_1                 | [1]   "args": "0xffffff504f4c590300000001000000000098053933000000000000000000000000000000000000000000000000000000070700006060610627610140396060602061062760c03960c051610627016101a0396040602061062760c03960c05160040135111561003957600080fd5b6040602060206106270160c03960c05161062701610220396020602060206106270160c03960c05160040135111561007057600080fd5b6101a080600060c052602060c020602082510161012060006003818352015b826101205160200211156100a2576100c4565b61012051602002850151610120518501555b815160010180835281141561008f575b50505050505061022080600160c052602060c020602082510161012060006002818352015b826101205160200211156100fc5761011e565b61012051602002850151610120518501555b81516001018083528114156100e9575b5050505050506101805160025561060f56600436101561000d576104d9565b600035601c52600051341561002157600080fd5b6318160ddd8114156100395760055460005260206000f35b63dd62ed3e81141561008d5760043560a01c1561005557600080fd5b60243560a01c1561006557600080fd5b600460043560e05260c052604060c02060243560e05260c052604060c0205460005260206000f35b63a9059cbb81141561013e5760043560a01c156100a957600080fd5b60033360e05260c052604060c0208054602435808210156100c957600080fd5b80820390509050815550600360043560e05260c052604060c02080546024358181830110156100f757600080fd5b8082019050905081555060243561014052600435337fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef6020610140a3600160005260206000f35b6323b872dd81141561023b5760043560a01c1561015a57600080fd5b60243560a01c1561016a57600080fd5b600360043560e05260c052604060c02080546044358082101561018c57600080fd5b80820390509050815550600360243560e05260c052604060c02080546044358181830110156101ba57600080fd5b80820190509050815550600460043560e05260c052604060c0203360e05260c052604060c0208054604435808210156101f257600080fd5b80820390509050815550604435610140526024356004357fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef6020610140a3600160005260206000f35b63095ea7b38114156102b45760043560a01c1561025757600080fd5b60243560043360e05260c052604060c02060043560e05260c052604060c0205560243561014052600435337f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b9256020610140a3600160005260206000f35b63ca44180381141561033f57600580546004358181830110156102d657600080fd5b8082019050905081555060033360e05260c052604060c020805460043581818301101561030257600080fd5b80820190509050815550600435610140523360007fddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef6020610140a3005b6306fdde038114156103e45760008060c052602060c020610180602082540161012060006003818352015b8261012051602002111561037d5761039f565b61012051850154610120516020028501525b815160010180835281141561036a575b50505050505061018051806101a001818260206001820306601f82010390500336823750506020610160526040610180510160206001820306601f8201039050610160f35b6395d89b418114156104895760018060c052602060c020610180602082540161012060006002818352015b8261012051602002111561042257610444565b61012051850154610120516020028501525b815160010180835281141561040f575b50505050505061018051806101a001818260206001820306601f82010390500336823750506020610160526040610180510160206001820306601f8201039050610160f35b63313ce5678114156104a15760025460005260206000f35b6370a082318114156104d75760043560a01c156104bd57600080fd5b600360043560e05260c052604060c0205460005260206000f35b505b60006000fd5b61013061060f0361013060003961013061060f036000f3000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000003444149000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034441490000000000000000000000000000000000000000000000000000000000"
web3_1                 | [1] }
web3_1                 | [1] [error]  JSONRPC Server Error: [bound estimateGas] Error: JSONRPCError: server error {"code":0,"message":"invalid exit code 12"} Error: JSONRPCError: server error {"code":0,"message":"invalid exit code 12"}
web3_1                 | [1]     at Proxy.<anonymous> (/code/godwoken-web3/node_modules/ckb-js-toolkit/dist/ckb-js-toolkit.node.js:1:51999)
web3_1                 | [1]     at runMicrotasks (<anonymous>)
web3_1                 | [1]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
web3_1                 | [1]     at async Eth.estimateGas (/code/godwoken-web3/packages/api-server/lib/methods/modules/eth.js:246:27)
web3_1                 | [1]     at async Eth.estimateGas (/code/godwoken-web3/packages/api-server/lib/methods/validator.js:32:20)
```

Network has been added to brownie via:
```
$ brownie networks add Godwoken-Dev godwokendev host=http://localhost:8024 chainid=0x3
Brownie v1.14.6 - Python development framework for Ethereum

SUCCESS: A new network 'godwokendev' has been added
  └─godwokendev
    ├─id: godwokendev
    ├─chainid: 0x3
    └─host: http://localhost:8024
```

When I'm looking at status code returned by web3 it shows: 12 which corresponds to: [EVMC_PRECOMPILE_FAILURE ](https://github.com/ethereum/evmc/blob/5915690317989b02fd73d5aa338e4edfa120a452/include/evmc/evmc.h#L273).

**Comment by Kuzirashi** [comment]
I modified the attached repository code to send transaction despite potential revert and it fails with different error:
```
ValueError: l2_transaction.raw is missing from_id!
error Command failed with exit code 1.
```

Code (https://github.com/Kuzirashi/brownie-contract-deploy-godwoken/blob/master/scripts/deploy.py, commit: https://github.com/Kuzirashi/brownie-contract-deploy-godwoken/commit/4d14878eb7af2820ba72777d8ae275bbbbef62f5):
```
DEPLOYER.deploy(ERC20, "DAI", "DAI", 18, gas_limit=8000000, gas_price=0, allow_revert=True)
```

Full log where first I test on Ganache and it works and then on Godwoken and it breaks:

```
➜  brownie-contract-deploy git:(master) yarn deploy:ganache                  
yarn run v1.22.10
$ brownie run scripts/deploy --network ganache
Brownie v1.14.6 - Python development framework for Ethereum

BrownieContractDeployProject is the active project.
Enter the password to unlock this account: 

Running 'scripts/deploy.py::main'...
deploy_tokens
Transaction sent: 0x33cca652e7504e0379510c7e74e8eb9dc624a5eb6d025c991d3eea4985533a62
  Gas price: 0.0 gwei   Gas limit: 8000000   Nonce: 2
  ERC20.constructor confirmed - Block: 3   Gas used: 429131 (5.36%)
  ERC20 deployed at: 0xC14bC37d09647CB9567CBeDDAc5f7e5E0875c452

coin_a deployed! (●'◡'●)
Done in 2.19s.
➜  brownie-contract-deploy git:(master) yarn deploy:godwoken                 
yarn run v1.22.10
$ brownie run scripts/deploy --network godwokendev
Brownie v1.14.6 - Python development framework for Ethereum

BrownieContractDeployProject is the active project.
Enter the password to unlock this account: 

Running 'scripts/deploy.py::main'...
deploy_tokens
  File "brownie/_cli/run.py", line 49, in main
    return_value, frame = run(
  File "brownie/project/scripts.py", line 103, in run
    return_value = f_locals[method_name](*args, **kwargs)
  File "./scripts/deploy.py", line 39, in main
    [coin_a] = deploy_tokens(_tx_params())
  File "./scripts/deploy.py", line 30, in deploy_tokens
    DEPLOYER.deploy(ERC20, "DAI", "DAI", 18, gas_limit=8000000, gas_price=0, allow_revert=True)
  File "brownie/network/account.py", line 465, in deploy
    exc = VirtualMachineError(e)
  File "brownie/exceptions.py", line 85, in __init__
    raise ValueError(exc["message"]) from None
ValueError: l2_transaction.raw is missing from_id!
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  brownie-contract-deploy git:(master) 
```

![image](https://user-images.githubusercontent.com/4950658/119658152-19c3cc00-be2d-11eb-9d6c-185ddcc54b8c.png)

cc @RetricSu @TheWaWaR

**Comment by RetricSu** [comment]
might not be related, but I see a `Error: l2_transaction.raw is missing from_id!` so wanna ask: what is the chain_id  used here in Brownie?

**Comment by Kuzirashi** [comment]
@RetricSu 

Chain id 3 is used: https://github.com/Kuzirashi/brownie-contract-deploy-godwoken/blob/master/package.json#L19

**Comment by RetricSu** [comment]
ok, 3 should be fine. usually `Error: l2_transaction.raw is missing from_id!` this err happend when web3 cannot find godwoken account id by the ethAddress which is the publicKey recovered from tx's signature. you can debug web3 components and print some info to check if the ethAddress is correct or if the signature recover process went wrong.
