### ISSUE TITLE
Error: libnode.so.72: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Flouse** [RetricSu/godwoken-kicker#8]
```
make init
make start 
```
and then I got the followed error in `docker_polyjuice_1` container:

```
+ cd /code/godwoken-examples
+ yarn workspace @godwoken-examples/runner clean
yarn workspace v1.22.10
yarn run v1.22.10
$ rm -rf ./db
Done in 0.10s.
Done in 0.62s.
+ cd packages/runner
+ npm start

> @godwoken-examples/runner@0.0.1 start /code/godwoken-examples/packages/runner
> LUMOS_CONFIG_FILE=./configs/lumos-config.json MODE=docker-compose ts-node-dev ./src/index

[INFO] 03:18:07 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.1.3)
Error: libnode.so.72: cannot open shared object file: No such file or directory
    at Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Object.nodeDevHook [as .node] (/code/godwoken-examples/node_modules/ts-node-dev/lib/hook.js:63:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/code/godwoken-examples/node_modules/xxhash/lib/xxhash.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/code/godwoken-examples/node_modules/source-map-support/source-map-support.js:547:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[ERROR] 03:18:16 Error: libnode.so.72: cannot open shared object file: No such file or directory
```

**Comment by Flouse** [comment]
I cleared the docker container and image of `docker_polyjuice_1` , and the error has gown away.
